<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVk5bvuh\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVk5bvuh/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVk5bvuh.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVk5bvuh\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVk5bvuh\appDevDebugProjectContainer([
    'container.build_hash' => 'Vk5bvuh',
    'container.build_id' => '54e9f442',
    'container.build_time' => 1737308013,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVk5bvuh');
